name: Lint Markdown with Proselint

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  proselint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install proselint
        run: |
          pip install --quiet proselint

      - name: Run proselint on all Markdown files
        run: |
          echo "Running proselint..."
          find . -name "*.md" -print0 | xargs -0 proselint
